version: '3'
services:          
    balance-stag-mega-sv:
        build: 
            context : .
            args:
                ENV: staging 

        container_name: balance-stag-mega-container
        restart: always
        ports:
            - "8880:80"
