

export const taxApply = {
  APPLY : 'APPLY',
  NO_APPLY : 'NO_APPLY',
}

export const fileType = {
  PRODUCT_STORE: 'PRODUCT_STORE',
  PRODUCT_SUPPLIER: 'PRODUCT_SUPPLIER',
  PRODUCT_IMPORT_PROMOTION: 'PRODUCT_IMPORT_PROMOTION',
  PRODUCT_IMPORT_IMAGE_DEFAULT: 'PRODUCT_IMPORT_IMAGE_DEFAULT'
}

export const approveStatus = {
  ALL: 'ALL',
  APPROVED: 'APPROVED',
  WAITING_APPROVE: 'WAITING_APPROVE',
  REJECTED: 'REJECTED',
  OUT_OF_STOCK: 'OUT_OF_STOCK',
  STOP_SELLING: 'STOP_SELLING',
  CANCELLED: 'CANCELLED',
}