const Util = (name, type) => {
  const array = {
    Login: '/auth/login',
    ForgotPass: '/auth/forgot-password',
    ResetPass: '/auth/reset-password',
    SendOTP: '/auth/send-otp',
    Dashboard: '/',
    // User
    User: '/user',
    'Quản lý người dùng': '/user',
    UserCreate: '/user/create',
    UserEdit: '/user/edit',
    // Hàng hoá
    'Quản lý hàng hóa': '/merchandise-managerment',
    Category: '/merchandise-managerment/category',
    'Danh mục': '/merchandise-managerment/category',
    CategoryCreate: '/merchandise-managerment/category/create',
    CategoryEdit: '/merchandise-managerment/category/edit',
    CategoryDetail: '/merchandise-managerment/category/detail',
    Product: '/merchandise-managerment/product',
    'Sản phẩm': '/merchandise-managerment/product',
    ProductCreate: '/merchandise-managerment/product/create',
    ProductEdit: '/merchandise-managerment/product/edit',
    ProductDetail: '/merchandise-managerment/product/detail',
    ProductImport: "/merchandise-managerment/product/import",
    // Supplier
    Supplier: '/supplier',
    'Quản lý nhà cung cấp': '/supplier',
    SupplierCreate: '/supplier/create',
    SupplierEdit: '/supplier/edit',
    SupplierProductDetail: '/supplier/product/detail',
    SupplierInfo: '/supplier/info',
    'Thông tin NCC': '/supplier/info',
    Revenue: '/supplier/revenue',
    'Doanh thu': '/supplier/revenue',
    Discount: '/supplier/discount',
    'Chiết khấu': '/supplier/discount',
    SupplierContract: '/supplier/contract',
    'Hợp đồng': '/supplier/contract',
    // Store
    "Quản lý cửa hàng": "/store-managerment",
    StoreCreate: "/store-managerment/create",
    StoreEdit: "/store-managerment/edit",
    StoreDetail: "/store-managerment/detail",
    StoreConnectSuppliper: "/store-managerment/connect-supplier/edit",
    ContractManagement: '/contract-management',
    "Quản lý hợp đồng": '/contract-management',
    'Đặt hàng': '/input-product/product',
    InputProduct: '/input-product/product',
    InputProductDetail: '/input-product/detail',
    CartDetail: '/cart',
    CartSalesDetail: '/cartSales',
    StoreInfo: '/store-management/information',
    'Thông tin cửa hàng': '/store-management/information',
    RevenueByProduct: '/store-management/revenue-by-product',
    'Doanh thu theo SP': '/store-management/revenue-by-product',
    RevenueByOrder: '/store-management/revenue-by-order',
    'Doanh thu theo ĐH': '/store-management/revenue-by-order',
    // InventoryManagement:'/store-management/inventory',
    // 'Quản lý kho':'/store-management/inventory',
    'Quản lý kho': '/inventory-managerment',
    'Nhập Hàng Trực Tiếp': '/inventory-managerment/promotional-goods',
    'PromotionalGoods': '/inventory-managerment/promotional-goods',
    'PromotionalGoodsCreate': '/inventory-managerment/promotional-goods/create',
    'PromotionalGoodsDetail': '/inventory-managerment/promotional-goods/detail',
    'PromotionalGoodsEdit': '/inventory-managerment/promotional-goods/edit',
    PromotionOrderDetail: '/promotion-order/detail',
    // Don hang
    OrderManagement: '/order',
    'Quản lý đơn hàng': '/order',
    OrderDetail: '/order/detail',
    OrderEdit: '/order/edit',
    // revenue management
    'Quản lý doanh thu': '/revenue-management',
    'Doanh thu CH': '/revenue-management/store',
    'Doanh thu NCC': '/revenue-management/supplier',
    'Chiết khấu NCC': '/revenue-management/discount',
    'RevenueManagement': '/revenue-management',
    'RevenueManagementStore': '/revenue-management/store',
    'RevenueManagementSupplier': '/revenue-management/supplier',
    'RevenueManagementDiscount': '/revenue-management/discount',

     // Connection
    ConnectManagement: '/connect-management',
    // ContractManagement: '/contract-management/connect',
    'Quản lý kết nối': '/connect-management',
    'Kết nối': '/connect-management/connect',
    Connect: '/connect-management/connect',
    // 'Danh sách hợp đồng': '/connect-management/contract',
    Contract: '/connect-management/contract',
    RequestDetail: '/connect-management/connect/detail',
    SampleContractBetweenStoreNSupplier: '/connect-management/sample-contract-store-supplier',
    ContractDetailBetweenStoreNSupplier: '/connect-management/contract-store-supplier/detail',
    SampleContract: '/contract-view',
    RevenueDetail: '/revenue/detail',
    MechandiseManagementDetail: '/merchandise-managerment/product/detail',
    DiscountDetail: '/discount-detail',
    // user infomation
    Profile: '/profile',
    'Thông tin cá nhân': '/profile',
    // Tax
    "Thuế": "/merchandise-managerment/tax",
    "Tax": "/merchandise-managerment/tax",
    // Quản lý kho
    // Hủy hàng
    DisposalGoods: '/inventory-managerment/disposal-goods',
    'Hủy hàng': '/inventory-managerment/disposal-goods',
    DisposalGoodsCreate: '/inventory-managerment/disposal-goods/create',
    DisposalGoodsDetail: '/inventory-managerment/disposal-goods/detail',
    DisposalGoodsEdit: '/inventory-managerment/disposal-goods/edit',
    // Trả hàng
    "Trả hàng": '/inventory-managerment/goods-return',
    GoodReturn: '/inventory-managerment/goods-return',
    GoodReturnCreate: '/inventory-managerment/goods-return/create',
    GoodReturnEdit: '/inventory-managerment/goods-return/edit',
    GoodReturnDetail: '/inventory-managerment/goods-return/detail',

    // Tồn kho
    InventoryManagement: '/inventory-managerment/inventory',
    'Tồn kho': '/inventory-managerment/inventory',
    InventoryCheck: '/inventory-managerment/inventory-check',
    'Kiểm kê': '/inventory-managerment/inventory-check',
    InventoryCheckCreate: '/inventory-managerment/inventory-check/create',
    InventoryCheckEdit: '/inventory-managerment/inventory-check/edit',

    ManageReturnGoods: '/merchandise-supplier-management/return-goods',
    'Quản lý trả hàng': '/merchandise-supplier-management/return-goods',
    ManageReturnGoodsDetail: '/merchandise-supplier-management/return-goods/detail',
    SupplierManagementByStore: '/supplier-management-by-store',
    'Quản lý NCC': '/supplier-management-by-store',

    // Store Non BAL
    ProductStore: "/merchandise-managerment/product/store",
    ProductStoreCreate: "/merchandise-managerment/product/store/create",
    ProductStoreDetail: "/merchandise-managerment/product/store/detail",
    ProductStoreEdit: "/merchandise-managerment/product/store/edit",

    // Branch
    'Quản lý chi nhánh': '/store-management/branch-management',
    BranchManagement: '/store-management/branch-management',
    BranchCreate: '/store-management/branch-management/create',
    BranchEdit: '/store-management/branch-management/edit',
    BranchDetail: '/store-management/branch-management/detail',
    // Non Balance
    ImportGoodsNonBal: '/inventory-managerment/import-goods-from-nonBal',
    'Nhập hàng N-Balance': '/inventory-managerment/import-goods-from-nonBal',
    ImportGoodsNonBalCreate: '/inventory-managerment/import-goods-from-nonBal/create',
    ImportGoodsNonBalDetail: '/inventory-managerment/import-goods-from-nonBal/detail',
    ImportGoodsNonBalEdit: '/inventory-managerment/import-goods-from-nonBal/edit',
    // Goods Transfer
    'Chuyển hàng': '/inventory-managerment/goods-transfer',
    GoodTransfer: '/inventory-managerment/goods-transfer',
    GoodTransferCreate: '/inventory-managerment/goods-transfer/create',
    GoodTransferEdit: '/inventory-managerment/goods-transfer/edit',
    GoodTransferDetail: '/inventory-managerment/goods-transfer/detail',
    GoodReceiveDetail: '/inventory-managerment/goods-receive/detail',
    // 'Chuyển hàng Admin': '/inventory-managerment/transfer-goods',
    'Quản lý chuyển hàng': '/inventory-managerment/transfer-goods',
    GoodTransferAdmin: '/inventory-managerment/transfer-goods',
    GoodTransferAdminDetail: '/inventory-managerment/transfer-goods/detail',
    StoreManageUserAdd: '/store-manage-user/create',
    StoreManageUserEdit: '/store-manage-user/edit',
    StoreManageUserDetail: '/store-manage-user/detail',
    // Báo cáo
    Report: '/report',
    'Báo cáo': '/report',
    'Xuất nhập tồn': '/report/export-import-exist',
    ExportImportExist: '/report/export-import-exist',
    'Danh sách phiếu kho': '/report/list-of-stock',
    ListOfStock: '/report/list-of-stock',
    // Quản lý khuyến mãi
    'Quản lý khuyến mãi': '/promotion-management',
    'PromotionManagement': '/promotion-management',
    'Quản lý voucher': '/promotion-management/vouchers',
    'VoucherManagement': '/promotion-management/vouchers',
    'VoucherManagementCreate': '/promotion-management/vouchers/create',
    'VoucherManagementEdit': '/promotion-management/vouchers/edit',
    // Cấu hình chung
    'Cấu hình chung': '/general-configuration',
    GeneralConfiguration: '/general-configuration',
    // Quản lý khách hàng
    'Quản lý khách hàng': '/sales-management-customer',
    'SalesManagementCustomer': '/sales-management-customer'
  }; // 💬 generate link to here


  const apis = {
    Cart: '/cart',
    Dashboard: '/dashboard',
    Category: '/category',
    Product: '/product',
    Util: '/util',
    Role: '/mt-role',
    User: '/user-admin',
    StoreSupplier: '/sub-organization',
    ConnectStoreSupplier: '/connect-store-supplier',
    OrderManagement: '/orders',
    ConnectManagement: '/connect-management',
    Order: '/orders',
    MerchandiseSuppliermanagement: '',
    StoreRequest: '/store-request',
    StoreRequestSupplier: '/store-request-supplier',
    StoreConnectSupplier: '/store-connect-supplier',
    ConnectContract: '/document-sub-organiztion',
    FileDocContract: '/file-doc-contract',
    Commission: '/sub-org-commision',
    CommissionPayment: '/sub-org-commision-payment',
    CommissionLine: '/sub-org-commision-line',
    InvoiceKiotViet: '/invoice-kiot-viet',
    InventoryProduct: '/inventory-product',
    InventoryOrder: '/inventory-order',
    InventoryOrderLineItem: '/inventory-order-line-item',
    Tax: "/mt-tax",
    OrderInvoice: '/order-invoice',
    InformationConnect: '/information-connect',
    file: '/file',
    SubOrganization: '/sub-organization',
    Report: '/inventory-report',
    Voucher: '/voucher',
    InventoryCheck:'/stocktake',
    Cronjob: '/cron-job',
    Unit: 'units',
    Customer: '/customer'

  }; // 💬 generate api to here

  switch (type) {
    case 'api':
      return apis[name];
    default:
      return array[name];
  }
};
export default Util;
